window.CERTIFICADOS = [
  {
    "codigo": "IC-002201",
    "nombre": "Percy Eugenio Mizare Huamán",
    "dni": "43057385",
    "curso": "Seguridad para Trabajos en Caliente",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002201.pdf"
  },
  {
    "codigo": "IC-002202",
    "nombre": "Percy Eugenio Mizare Huamán",
    "dni": "43057385",
    "curso": "Seguridad para Trabajos en Altura",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002202.pdf"
  },
  {
    "codigo": "IC-002203",
    "nombre": "Percy Eugenio Mizare Huamán",
    "dni": "43057385",
    "curso": "Seguridad en Izaje de Cargas",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002203.pdf"
  },
  {
    "codigo": "IC-002204",
    "nombre": "Percy Eugenio Mizare Huamán",
    "dni": "43057385",
    "curso": "Uso de Extintores",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002204.pdf"
  },
  {
    "codigo": "IC-002205",
    "nombre": "Carlos Bladimir Berrocal Huamán",
    "dni": "46327710",
    "curso": "Seguridad para Trabajos en Caliente",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002205.pdf"
  },
  {
    "codigo": "IC-002206",
    "nombre": "Carlos Bladimir Berrocal Huamán",
    "dni": "46327710",
    "curso": "Seguridad para Trabajos en Altura",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002206.pdf"
  },
  {
    "codigo": "IC-002207",
    "nombre": "Carlos Bladimir Berrocal Huamán",
    "dni": "46327710",
    "curso": "Seguridad en Izaje de Cargas",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002207.pdf"
  },
  {
    "codigo": "IC-002208",
    "nombre": "Carlos Bladimir Berrocal Huamán",
    "dni": "46327710",
    "curso": "Uso de Extintores",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002208.pdf"
  },
  {
    "codigo": "IC-002209",
    "nombre": "Oliver Schmeling Mendoza Montoya",
    "dni": "41674630",
    "curso": "Seguridad para Trabajos en Caliente",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002209.pdf"
  },
  {
    "codigo": "IC-002210",
    "nombre": "Oliver Schmeling Mendoza Montoya",
    "dni": "41674630",
    "curso": "Seguridad para Trabajos en Altura",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002210.pdf"
  },
  {
    "codigo": "IC-002211",
    "nombre": "Oliver Schmeling Mendoza Montoya",
    "dni": "41674630",
    "curso": "Seguridad en Izaje de Cargas",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002211.pdf"
  },
  {
    "codigo": "IC-002212",
    "nombre": "Oliver Schmeling Mendoza Montoya",
    "dni": "41674630",
    "curso": "Uso de Extintores",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002212.pdf"
  },
  {
    "codigo": "IC-002213",
    "nombre": "Gianmarco Josué Granda Anicama",
    "dni": "72768349",
    "curso": "Seguridad para Trabajos en Caliente",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002213.pdf"
  },
  {
    "codigo": "IC-002214",
    "nombre": "Gianmarco Josué Granda Anicama",
    "dni": "72768349",
    "curso": "Seguridad para Trabajos en Altura",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002214.pdf"
  },
  {
    "codigo": "IC-002215",
    "nombre": "Gianmarco Josué Granda Anicama",
    "dni": "72768349",
    "curso": "Seguridad en Izaje de Cargas",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002215.pdf"
  },
  {
    "codigo": "IC-002216",
    "nombre": "Gianmarco Josué Granda Anicama",
    "dni": "72768349",
    "curso": "Uso de Extintores",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002216.pdf"
  },
{
  "codigo": "IC-001142",
  "nombre": "RIVADENEYRA CELIS DANBER ISAAC",
  "dni": "76458032",
  "curso": "Seguridad para Trabajos en Altura",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001142.pdf"
},
{
  "codigo": "IC-001143",
  "nombre": "RIVADENEYRA CELIS DANBER ISAAC",
  "dni": "76458032",
  "curso": "Seguridad para Trabajos en Caliente",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001143.pdf"
},
{
  "codigo": "IC-001144",
  "nombre": "RIVADENEYRA CELIS DANBER ISAAC",
  "dni": "76458032",
  "curso": "Seguridad en Izaje de Cargas",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001144.pdf"
},
{
  "codigo": "IC-001145",
  "nombre": "RIVADENEYRA CELIS DANBER ISAAC",
  "dni": "76458032",
  "curso": "Armado y Uso de Andamios",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001145.pdf"
},
{
  "codigo": "IC-001146",
  "nombre": "LEDESMA CURO GUSTAVO RICARDO",
  "dni": "40793648",
  "curso": "Seguridad para Trabajos en Altura",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001146.pdf"
},
{
  "codigo": "IC-001147",
  "nombre": "LEDESMA CURO GUSTAVO RICARDO",
  "dni": "40793648",
  "curso": "Seguridad para Trabajos en Caliente",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001147.pdf"
},
{
  "codigo": "IC-001148",
  "nombre": "LEDESMA CURO GUSTAVO RICARDO",
  "dni": "40793648",
  "curso": "Seguridad en Izaje de Cargas",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001148.pdf"
},
{
  "codigo": "IC-001149",
  "nombre": "LEDESMA CURO GUSTAVO RICARDO",
  "dni": "40793648",
  "curso": "Armado y Uso de Andamios",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001149.pdf"
},
{
  "codigo": "IC-001150",
  "nombre": "YUCRA ESCRIBA ANDRES",
  "dni": "41803732",
  "curso": "Seguridad para Trabajos en Altura",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001150.pdf"
},
{
  "codigo": "IC-001151",
  "nombre": "YUCRA ESCRIBA ANDRES",
  "dni": "41803732",
  "curso": "Seguridad para Trabajos en Caliente",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001151.pdf"
},
{
  "codigo": "IC-001152",
  "nombre": "YUCRA ESCRIBA ANDRES",
  "dni": "41803732",
  "curso": "Seguridad en Izaje de Cargas",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001152.pdf"
},
{
  "codigo": "IC-001153",
  "nombre": "YUCRA ESCRIBA ANDRES",
  "dni": "41803732",
  "curso": "Armado y Uso de Andamios",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001153.pdf"
},
{
  "codigo": "IC-001154",
  "nombre": "FRANCO ZAVALETA BRUCE MAURICIO",
  "dni": "75954276",
  "curso": "Seguridad para Trabajos en Altura",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001154.pdf"
},
{
  "codigo": "IC-001155",
  "nombre": "FRANCO ZAVALETA BRUCE MAURICIO",
  "dni": "75954276",
  "curso": "Seguridad para Trabajos en Caliente",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001155.pdf"
},
{
  "codigo": "IC-001156",
  "nombre": "FRANCO ZAVALETA BRUCE MAURICIO",
  "dni": "75954276",
  "curso": "Seguridad en Izaje de Cargas",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001156.pdf"
},
{
  "codigo": "IC-001157",
  "nombre": "FRANCO ZAVALETA BRUCE MAURICIO",
  "dni": "75954276",
  "curso": "Armado y Uso de Andamios",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001157.pdf"
},
{
  "codigo": "IC-001158",
  "nombre": "SALDAÑA MONDRAGON VICTOR DAVID",
  "dni": "70659561",
  "curso": "Seguridad para Trabajos en Altura",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001158.pdf"
},
{
  "codigo": "IC-001159",
  "nombre": "SALDAÑA MONDRAGON VICTOR DAVID",
  "dni": "70659561",
  "curso": "Seguridad para Trabajos en Caliente",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001159.pdf"
},
{
  "codigo": "IC-001160",
  "nombre": "SALDAÑA MONDRAGON VICTOR DAVID",
  "dni": "70659561",
  "curso": "Seguridad en Izaje de Cargas",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001160.pdf"
},
{
  "codigo": "IC-001161",
  "nombre": "SALDAÑA MONDRAGON VICTOR DAVID",
  "dni": "70659561",
  "curso": "Armado y Uso de Andamios",
  "horas": "08 horas académicas",
  "emision": "Agosto de 2026",
  "vencimiento": "Agosto de 2027",
  "estado": "VIGENTE",
  "empresa": "VAP INDUSTRIAL SOLUTIONS S.A.C.",
  "instructor": "Ing. Misael Beteta Montoya",
  "pdf": "pdf/IC-001161.pdf"
}];
