window.CERTIFICADOS = [
  {
    "codigo": "IC-002201",
    "nombre": "Percy Eugenio Mizare Huamán",
    "dni": "43057385",
    "curso": "Seguridad para Trabajos en Caliente",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002201.pdf"
  },
  {
    "codigo": "IC-002202",
    "nombre": "Percy Eugenio Mizare Huamán",
    "dni": "43057385",
    "curso": "Seguridad para Trabajos en Altura",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002202.pdf"
  },
  {
    "codigo": "IC-002203",
    "nombre": "Percy Eugenio Mizare Huamán",
    "dni": "43057385",
    "curso": "Seguridad en Izaje de Cargas",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002203.pdf"
  },
  {
    "codigo": "IC-002204",
    "nombre": "Percy Eugenio Mizare Huamán",
    "dni": "43057385",
    "curso": "Uso de Extintores",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002204.pdf"
  },
  {
    "codigo": "IC-002205",
    "nombre": "Carlos Bladimir Berrocal Huamán",
    "dni": "46327710",
    "curso": "Seguridad para Trabajos en Caliente",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002205.pdf"
  },
  {
    "codigo": "IC-002206",
    "nombre": "Carlos Bladimir Berrocal Huamán",
    "dni": "46327710",
    "curso": "Seguridad para Trabajos en Altura",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002206.pdf"
  },
  {
    "codigo": "IC-002207",
    "nombre": "Carlos Bladimir Berrocal Huamán",
    "dni": "46327710",
    "curso": "Seguridad en Izaje de Cargas",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002207.pdf"
  },
  {
    "codigo": "IC-002208",
    "nombre": "Carlos Bladimir Berrocal Huamán",
    "dni": "46327710",
    "curso": "Uso de Extintores",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002208.pdf"
  },
  {
    "codigo": "IC-002209",
    "nombre": "Oliver Schmeling Mendoza Montoya",
    "dni": "41674630",
    "curso": "Seguridad para Trabajos en Caliente",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002209.pdf"
  },
  {
    "codigo": "IC-002210",
    "nombre": "Oliver Schmeling Mendoza Montoya",
    "dni": "41674630",
    "curso": "Seguridad para Trabajos en Altura",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002210.pdf"
  },
  {
    "codigo": "IC-002211",
    "nombre": "Oliver Schmeling Mendoza Montoya",
    "dni": "41674630",
    "curso": "Seguridad en Izaje de Cargas",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002211.pdf"
  },
  {
    "codigo": "IC-002212",
    "nombre": "Oliver Schmeling Mendoza Montoya",
    "dni": "41674630",
    "curso": "Uso de Extintores",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002212.pdf"
  },
  {
    "codigo": "IC-002213",
    "nombre": "Gianmarco Josué Granda Anicama",
    "dni": "72768349",
    "curso": "Seguridad para Trabajos en Caliente",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002213.pdf"
  },
  {
    "codigo": "IC-002214",
    "nombre": "Gianmarco Josué Granda Anicama",
    "dni": "72768349",
    "curso": "Seguridad para Trabajos en Altura",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002214.pdf"
  },
  {
    "codigo": "IC-002215",
    "nombre": "Gianmarco Josué Granda Anicama",
    "dni": "72768349",
    "curso": "Seguridad en Izaje de Cargas",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002215.pdf"
  },
  {
    "codigo": "IC-002216",
    "nombre": "Gianmarco Josué Granda Anicama",
    "dni": "72768349",
    "curso": "Uso de Extintores",
    "horas": "08 horas académicas",
    "emision": "Julio de 2026",
    "vencimiento": "Julio de 2027",
    "estado": "VIGENTE",
    "empresa": "FIRELIGHT PROTECTION E.I.R.L.",
    "instructor": "Ing. (B) José Garrido",
    "pdf": "pdf/IC-002216.pdf"
  }
];
